<a href="https://colab.research.google.com/github/libra3910/diveintocode-ml/blob/master/Copy_of_ML2101_WEEK4_beforeclass3_object.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# WEEK3　授業前課題3　オブジェクト指向の活用　by　遠藤伸

# 【問題1】これまで利用してきたクラスの列挙

### ①Pandasのオブジェクト
```PY
DataFrame、
Series、
Index
```

### ②matplotlibのオブジェクト
```PY
colors：ListedColormap、
matplotlib
patches
```

### ③scikit-learnのオブジェクト
```PY
1.前処理：
　model_selection：train_test_split、
　preprocessing：StandardScaler
2.学習モデル：
　neighbors：KNeighborsClassifier、
　linear_model：LinearRegression、
　svm：SVR、
　pipeline：make_pipeline、
　tree：DecisionTreeRegressor、plot_tree、
　ensemble：RandomForestRegressor
評価：
　metrics：mean_squared_error、accuracy_score、precision_score、recall_score、f1_score、confusion_matrix
```

# 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙

### ①Pandasオブジェクト
```PY
DataFrame：
　メソッド：concat()、head()、sum()、isna()、describe()、info()
　属性：loc、iloc、index
Series：
　メソッド：head()、sum()、isna()、describe()、info()
　属性：loc、iloc、index
```

### ②matplotlibのオブジェクト
```PY
matplotlib
　メソッド：scatterplot()、boxplot()、violinplot()、pie()、pairplot()
patches
　メソッド：Patch
```

### ③scikit-learnのオブジェクト
```PY
1.前処理：
　model_selection：train_test_split、
　preprocessing：StandardScaler
　　メソッド：fit()、transform()
2.学習モデル：
　neighbors：KNeighborsClassifier、
    メソッド：fit()、predict()
　linear_model：LinearRegression、
　　メソッド：fit()、predict()、score()
    インスタンス変数：coef_、intercept_
　svm：SVR、
　pipeline：make_pipeline、
　tree：DecisionTreeRegressor、plot_tree、
　　メソッド：fit()、predict()
　ensemble：RandomForestRegressor
　　メソッド：fit()、predict()
評価：
　metrics：mean_squared_error、accuracy_score、precision_score、recall_score、f1_score、confusion_matrix
```

# 【問題3】標準化クラスをスクラッチで作成

In [ ]:
import numpy as np
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = np.mean(X, axis=0)
        self.var_ = np.sum((X - self.mean_)**2,axis=0)

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X - self.mean_) / np.sqrt(self.var_)
        return X_scaled

In [ ]:
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.764 0.849 0.105 0.056]
[[ 0.27457726  0.20620527 -0.15430335 -0.08451543]
 [ 0.04576288 -0.33644017 -0.15430335 -0.08451543]
 [-0.1830515  -0.119382   -0.46291005 -0.08451543]
 [-0.2974587  -0.22791109  0.15430335 -0.08451543]
 [ 0.16017007  0.31473436 -0.15430335 -0.08451543]
 [ 0.61779883  0.64032162  0.77151675  0.76063883]
 [-0.2974587   0.09767618 -0.15430335  0.3380617 ]
 [ 0.16017007  0.09767618  0.15430335 -0.08451543]
 [-0.52627308 -0.44496926 -0.15430335 -0.08451543]
 [ 0.04576288 -0.22791109  0.15430335 -0.50709255]]


In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
scaler.fit(X)

StandardScaler()

In [ ]:
scaler.mean_

array([4.86, 3.31, 1.45, 0.22])

In [ ]:
scaler.var_

array([0.0764, 0.0849, 0.0105, 0.0056])

In [ ]:
X_std2 = scaler.transform(X)

In [ ]:
X_std2

array([[ 0.86828953,  0.65207831, -0.48795004, -0.26726124],
       [ 0.14471492, -1.06391725, -0.48795004, -0.26726124],
       [-0.57885968, -0.37751902, -1.46385011, -0.26726124],
       [-0.94064699, -0.72071813,  0.48795004, -0.26726124],
       [ 0.50650222,  0.99527742, -0.48795004, -0.26726124],
       [ 1.95365143,  2.02487476,  2.43975018,  2.40535118],
       [-0.94064699,  0.3088792 , -0.48795004,  1.06904497],
       [ 0.50650222,  0.3088792 ,  0.48795004, -0.26726124],
       [-1.66422159, -1.40711636, -0.48795004, -0.26726124],
       [ 0.14471492, -0.72071813,  0.48795004, -1.60356745]])

# 【問題4】 四則演算を行うクラスの作成

In [ ]:
class ExampleClass():
    """
    説明用の簡単なクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2

    def subtract(self, value3):
        """
        受け取った引数をself.valueから差し引く
        """
        self.value -= value3
        
    def multiple(self, value4):
        """
        受け取った引数をself.valueに乗算する
        """
        self.value *= value4

    def divide(self, value5):
        """
        受け取った引数をself.valueに除算する
        """
        self.value /= value5

example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value add (5 + 3): {}".format(example.value))
example.subtract(3)
print("value subtract (8 - 3): {}".format(example.value))
example.multiple(3)
print("value multiple (5 * 3): {}".format(example.value))
example.divide(3)
print("value devide (15 / 3): {}".format(example.value))


初期値5が設定されました
value : 5
value add (5 + 3): 8
value subtract (8 - 3): 5
value multiple (5 * 3): 15
value devide (15 / 3): 5.0
