<a href="https://colab.research.google.com/github/libra3910/diveintocode-ml/blob/master/ML2101%E6%9C%9F_WEEK2_%E9%81%A0%E8%97%A4%E4%BC%B8_%E6%8E%88%E6%A5%AD%E5%89%8D%E8%AA%B2%E9%A1%8C3_%E8%A1%8C%E5%88%97%E7%A9%8D%E3%81%AE%E3%82%B9%E3%82%AF%E3%83%A9%E3%83%83%E3%83%81.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

【問題1】行列積を手計算する

A = [[([-1,2,3] * [0,0,2]), ([-1,2,3] * [2,2,9]), ([-1,2,3] * [1,-8,-1])],
     [([4,-5,6] * [0,0,2]), ([4,-5,6] * [2,2,9]), ([4,-5,6] * [1,-8,-1])],
     [([7,8,-9] * [0,0,2]), ([7,8,-9] * [2,2,9]), ([7,8,-9] * [1,-8,-1])]]
  
  = [[(-1 * 0 + 2 * 0 + 3 * 2), (-1 * 2+ 2 * 2 + 3 * 9), (-1 * 1 + 2 * -8 + 3 * -1)]
     [(4 * 0 + -5 * 0 + 6 * 2), (4 * 2 + -5 * 2 + 6 * 9), (4 * 1 + -5 * -8 + 6 * -1)]
     [(7 * 0 + 8 * 0 + -9 * 2), (7 * 2 + 8 * 2 + -9 * 9), (7 * 1 + 8 * -8 + -9 * -1)]]
  
  = [[  6, 29,-20],
     [ 12, 52, 38],
     [-18,-51,-48]]

【問題2】NumPyの関数による計算

In [ ]:
import numpy as np
a = np.array([[-1,2,3],[4,-5,6],[7,8,-9]])
b = np.array([[0,2,1],[0,2,-8],[2,9,-1]])

A = np.matmul(a,b)
A

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [ ]:
B = np.dot(a,b)
B

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [ ]:
C = a@b
C

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

【問題3】ある要素の計算を実装

In [ ]:
n = 3
D = []
for i in range(n):
  for j in range(n):
    mid_val = 0
    for k in range(n):
      mid_val += a[i, k] * b[k, j]
    D.append(mid_val)
D

[6, 29, -20, 12, 52, 38, -18, -51, -48]

【問題4】行列積を行う関数の作成

In [ ]:
def matrix_product(a,b):
  n = len(a)
  D = []
  for i in range(n):
    for j in range(n):
      mid_val = 0
      for k in range(n):
        mid_val += a[i, k] * b[k, j]
      D.append(mid_val)
  return(D)

a2 = np.array([[-1,2,3,4],[4,-5,6,7],[7,8,-9,0],[3,5,6,-7]])
b2 = np.array([[0,2,1,0],[0,2,-8,6],[2,9,-1,3],[4,5,6,-7]])
print(matrix_product(a2,b2))

[22, 49, 4, -7, 40, 87, 80, -61, -18, -51, -48, 21, -16, 35, -85, 97]


【問題5】計算が定義されない入力を判定する

In [ ]:
def matrix_product(a,b):
  l = a.shape
  m = b.shape
  if (l[1] == m[0]):
    n = len(a)
    D = []
    for i in range(n):
      for j in range(n):
        mid_val = 0
        for k in range(n):
          mid_val += a[i, k] * b[k, j]
        D.append(mid_val)
    return(D)
  else:
      return("cannot be multiple: {}×{}".format(l[1],m[0]))

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
print(matrix_product(d_ndarray,e_ndarray))
#print(matrix_product(a2,b2))

cannot be multiple: 3×2


【問題6】転置

In [ ]:
print(matrix_product(d_ndarray, np.transpose(e_ndarray)))

[25, -16, -76, 49]


In [ ]:
print(matrix_product(d_ndarray, e_ndarray.T))

[25, -16, -76, 49]
